create extension if not exists "pgcrypto";

create table if not exists public.users (
  id integer generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  email text,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create or replace function public.update_updated_at_column()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.users (auth_user_id, email)
  values (new.id, new.email)
  on conflict (auth_user_id) do update
  set email = excluded.email,
      updated_at = timezone('utc'::text, now());

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of email on auth.users
for each row execute procedure public.handle_new_auth_user();

insert into public.users (auth_user_id, email)
select id, email
from auth.users
on conflict (auth_user_id) do nothing;

create or replace function public.current_user_profile_id()
returns integer
language sql
stable
as $$
  select id from public.users where auth_user_id = auth.uid()
$$;

create table if not exists public.product (
  id integer generated by default as identity primary key,
  user_id integer not null default public.current_user_profile_id() references public.users(id) on delete cascade,
  name varchar(255) not null,
  stock integer not null default 0 check (stock >= 0),
  price double precision not null default 0 check (price >= 0),
  unit text not null,
  description text,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.product_sold (
  id integer generated by default as identity primary key,
  product_id integer not null references public.product(id) on delete cascade,
  total integer not null check (total > 0),
  price double precision not null default 0 check (price >= 0),
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists idx_product_user_id on public.product(user_id);
create index if not exists idx_product_name on public.product(name);
create index if not exists idx_product_sold_product_id on public.product_sold(product_id);

drop trigger if exists users_set_updated_at on public.users;
create trigger users_set_updated_at
before update on public.users
for each row execute procedure public.update_updated_at_column();

drop trigger if exists product_set_updated_at on public.product;
create trigger product_set_updated_at
before update on public.product
for each row execute procedure public.update_updated_at_column();

drop trigger if exists product_sold_set_updated_at on public.product_sold;
create trigger product_sold_set_updated_at
before update on public.product_sold
for each row execute procedure public.update_updated_at_column();

alter table public.users enable row level security;
alter table public.product enable row level security;
alter table public.product_sold enable row level security;

drop policy if exists "users_select_own_profile" on public.users;
create policy "users_select_own_profile"
on public.users
for select
to authenticated
using ((select auth.uid()) = auth_user_id);

drop policy if exists "users_update_own_profile" on public.users;
create policy "users_update_own_profile"
on public.users
for update
to authenticated
using ((select auth.uid()) = auth_user_id)
with check ((select auth.uid()) = auth_user_id);

drop policy if exists "product_select_own_rows" on public.product;
create policy "product_select_own_rows"
on public.product
for select
to authenticated
using (user_id = (select public.current_user_profile_id()));

drop policy if exists "product_insert_own_rows" on public.product;
create policy "product_insert_own_rows"
on public.product
for insert
to authenticated
with check (user_id = (select public.current_user_profile_id()));

drop policy if exists "product_update_own_rows" on public.product;
create policy "product_update_own_rows"
on public.product
for update
to authenticated
using (user_id = (select public.current_user_profile_id()))
with check (user_id = (select public.current_user_profile_id()));

drop policy if exists "product_delete_own_rows" on public.product;
create policy "product_delete_own_rows"
on public.product
for delete
to authenticated
using (user_id = (select public.current_user_profile_id()));

drop policy if exists "product_sold_select_own_rows" on public.product_sold;
create policy "product_sold_select_own_rows"
on public.product_sold
for select
to authenticated
using (
  exists (
    select 1
    from public.product p
    where p.id = product_sold.product_id
      and p.user_id = (select public.current_user_profile_id())
  )
);

drop policy if exists "product_sold_insert_own_rows" on public.product_sold;
create policy "product_sold_insert_own_rows"
on public.product_sold
for insert
to authenticated
with check (
  exists (
    select 1
    from public.product p
    where p.id = product_sold.product_id
      and p.user_id = (select public.current_user_profile_id())
  )
);

drop policy if exists "product_sold_update_own_rows" on public.product_sold;
create policy "product_sold_update_own_rows"
on public.product_sold
for update
to authenticated
using (
  exists (
    select 1
    from public.product p
    where p.id = product_sold.product_id
      and p.user_id = (select public.current_user_profile_id())
  )
)
with check (
  exists (
    select 1
    from public.product p
    where p.id = product_sold.product_id
      and p.user_id = (select public.current_user_profile_id())
  )
);

drop policy if exists "product_sold_delete_own_rows" on public.product_sold;
create policy "product_sold_delete_own_rows"
on public.product_sold
for delete
to authenticated
using (
  exists (
    select 1
    from public.product p
    where p.id = product_sold.product_id
      and p.user_id = (select public.current_user_profile_id())
  )
);
